-- ============================================================================
-- Hyprland Configuration — Deluxe Edition
-- ============================================================================
--
-- Lua config. Hyprland 0.55 deprecated the hyprlang `.conf` format and 0.57
-- removes it; when both files exist this one wins, so the old hyprland.conf is
-- kept alongside purely as a rollback (delete this file and it takes over).
--
-- Reference: /usr/share/hypr/hyprland.lua (shipped by the package) and
-- /usr/share/hypr/stubs/hl.meta.lua (the API stubs).

------------------------------------------------------------------ MONITORS --
hl.monitor({ output = "", mode = "highres@highrr", position = "0x0", scale = 1.0 })
hl.monitor({ output = "", mode = "highres@highrr", position = "auto",  scale = 1.0 })

--------------------------------------------------------------- ENVIRONMENT --
hl.env("XCURSOR_SIZE", "48")
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("GTK_THEME", "Dracula")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

-- Machine-local files, each generated by setup.sh:
--   env-local   NVIDIA env vars and DRM devices, derived from the hardware
--   polkit-local  the polkit agent this release actually ships
--
-- pcall, not require, on purpose. `source =` in hyprlang failed softly on a
-- missing file; a bare require() raises, and a raised error in a Lua config
-- registers NO binds at all and drops Hyprland into emergency mode with only
-- SUPER+Q. A machine missing one generated file should lose that file's
-- settings, not its keyboard.
local function optional(mod)
    local ok, err = pcall(require, mod)
    if not ok then
        -- print(), not hl.log(): there is no hl.log, and this is the error
        -- path -- a call that does not exist here would defeat the whole
        -- point. print is plain Lua and lands in the Hyprland log.
        print("hyprland.lua: optional module '" .. mod .. "' not loaded: " .. tostring(err))
    end
    return ok
end

optional("env-local")
optional("polkit-local")

--------------------------------------------------------------------- INPUT --
hl.config({
    input = {
        kb_layout    = "us",
        follow_mouse = 1,
        sensitivity  = 0.5,
        touchpad = {
            natural_scroll = true,
            drag_lock      = true,
            -- tap_and_drag, not "tap-and-drag": hyprlang spelled config
            -- keys with hyphens, the Lua API uses underscores throughout.
            tap_and_drag   = true,
        },
    },
})

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

hl.config({
    gestures = {
        workspace_swipe_distance     = 300,
        workspace_swipe_cancel_ratio = 0.3,
    },
})

------------------------------------------------------------ LOOK AND FEEL --
hl.config({
    general = {
        gaps_in     = 5,
        gaps_out    = 10,
        border_size = 2,
        col = {
            active_border   = { colors = { "rgba(33ccffee)", "rgba(0000FFee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        layout           = "dwindle",
        resize_on_border = true,
    },

    cursor = {
        -- Overridden to true on machines whose display hangs off a second GPU;
        -- see local.lua at the bottom of this file.
        no_hardware_cursors = false,
    },

    misc = {
        disable_hyprland_logo        = true,
        disable_splash_rendering     = true,
        animate_manual_resizes       = true,
        animate_mouse_windowdragging = true,

        -- Explicitly off. NVIDIA's DRM KMS driver (595 branch) forces every
        -- VRR-capable display into VRR mode by default, which shows up as
        -- heavy pulsing/flicker in fullscreen. Leaving this at 0 is the fix;
        -- the alternative is the nvidia_modeset conceal_vrr_caps module
        -- parameter. If you have a genuine FreeSync/G-Sync panel and want it,
        -- set 2 (fullscreen only) and watch for flicker.
        vrr = 0,
    },

    decoration = {
        rounding         = 10,
        active_opacity   = 1.0,
        inactive_opacity = 0.9,
        dim_inactive     = true,
        dim_strength     = 0.1,
        blur = {
            enabled    = true,
            size       = 10,
            passes     = 3,
            xray       = false,
            noise      = 0.02,
            contrast   = 1.0,
            brightness = 1.0,
            vibrancy   = 0.2,
            popups     = true,
        },
        shadow = {
            enabled      = true,
            range        = 15,
            render_power = 3,
            color        = "rgba(1a1a1aee)",
        },
    },

    dwindle = {
        preserve_split = true,
        smart_split    = false,
        smart_resizing = true,
    },
})

---------------------------------------------------------------- ANIMATIONS --
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.22, 1 },    { 0.36, 1 } } })
hl.curve("easeInQuint",  { type = "bezier", points = { { 0.64, 0 },    { 0.78, 0 } } })
hl.curve("easeOutExpo",  { type = "bezier", points = { { 0.16, 1 },    { 0.3,  1 } } })
hl.curve("easeInExpo",   { type = "bezier", points = { { 0.7,  0 },    { 0.84, 0 } } })
hl.curve("liner",        { type = "bezier", points = { { 1,    1 },    { 1,    1 } } })
hl.curve("smooth",       { type = "bezier", points = { { 0.4,  0 },    { 0.2,  1 } } })

hl.config({ animations = { enabled = true } })

hl.animation({ leaf = "windows",          enabled = true, speed = 5,  bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 5,  bezier = "easeOutQuint", style = "popin 80%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 4,  bezier = "easeInQuint",  style = "popin 80%" })
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 5,  bezier = "smooth",       style = "slide" })
hl.animation({ leaf = "fade",             enabled = true, speed = 5,  bezier = "smooth" })
hl.animation({ leaf = "fadeIn",           enabled = true, speed = 4,  bezier = "easeOutExpo" })
hl.animation({ leaf = "fadeOut",          enabled = true, speed = 4,  bezier = "easeInExpo" })
hl.animation({ leaf = "border",           enabled = true, speed = 10, bezier = "smooth" })
hl.animation({ leaf = "borderangle",      enabled = true, speed = 80, bezier = "liner",        style = "loop" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 5,  bezier = "easeOutQuint", style = "slidefade 30%" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 5,  bezier = "easeOutExpo",  style = "slidevert" })
hl.animation({ leaf = "layers",           enabled = true, speed = 4,  bezier = "easeOutQuint", style = "popin 90%" })

----------------------------------------------------------------- AUTOSTART --
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("~/.local/bin/awww-daemon")
    hl.exec_cmd("sleep 3 && ~/.local/bin/awww img --transition-type center --transition-step 2 --transition-fps 60 ~/Pictures/Wallpapers/current.jpg")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("swaync")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("swayidle -w timeout 3600 '~/.local/bin/lock-screen' timeout 3660 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep '~/.local/bin/lock-screen'")
end)

-------------------------------------------------------------- WINDOW RULES --
local function float(name, match)
    hl.window_rule({ name = name, match = match, float = true })
end

float("float-pavucontrol",  { class = "^(pavucontrol)$" })
float("float-blueman",      { class = "^(blueman-manager)$" })
float("float-nm-editor",    { class = "^(nm-connection-editor)$" })
float("float-seahorse",     { class = "^(org.gnome.seahorse.Application)$" })
float("float-file-upload",  { title = "^(File Upload)(.*)$" })
float("float-save-as",      { title = "^(Save As)(.*)$" })
float("float-open-file",    { title = "^(Open File)(.*)$" })
float("float-portal-gtk",   { class = "^(xdg-desktop-portal-gtk)$" })
float("float-calculator",   { class = "^(org.gnome.Calculator)$" })
float("float-thunar-progress", { class = "^(thunar)$", title = "^(File Operation Progress)$" })

hl.window_rule({
    name  = "rofi",
    match = { class = "^(Rofi)$" },
    float = true, stay_focused = true, dim_around = true,
})

hl.window_rule({
    name  = "picture-in-picture",
    match = { title = "^(Picture-in-Picture)$" },
    float = true, pin = true,
    size  = "480 270",
    move  = "100%-490 100%-280",
})

hl.window_rule({
    name      = "scratchpad",
    match     = { class = "^(scratchpad)$" },
    float     = true,
    size      = "80% 60%",
    center    = true,
    animation = "slide",
})

for _, ns in ipairs({ "swaync-control-center", "swaync-notification-window" }) do
    hl.layer_rule({ name = "blur-" .. ns, match = { namespace = ns }, blur = true, ignore_alpha = 1 })
end

------------------------------------------------- SPECIAL WORKSPACES --------
hl.workspace_rule({ workspace = "special:scratchpad", on_created_empty = "kitty --class scratchpad" })
hl.workspace_rule({ workspace = "special:music",      on_created_empty = "kitty --class scratchpad -e playerctl metadata --follow" })

--------------------------------------------------------------- KEYBINDINGS --
local mainMod = "SUPER"
local function exec(keys, cmd, opts) hl.bind(keys, hl.dsp.exec_cmd(cmd), opts) end

-- Wallpaper cycling
exec("Home", "~/.local/bin/wallpaper-cycle prev")
exec("End",  "~/.local/bin/wallpaper-cycle next")

-- Apps
exec(mainMod .. " + RETURN", "rofi -show drun -theme spotlight-dark")
exec(mainMod .. " + T", "kitty")
exec(mainMod .. " + X", "wlogout --protocol layer-shell")
exec(mainMod .. " + B", "firefox")
exec(mainMod .. " + ALT + B", "chromium-browser")
exec(mainMod .. " + F", "thunar")
exec(mainMod .. " + K", "seahorse")
exec(mainMod .. " + A", "pavucontrol")
exec(mainMod .. " + S", "signal-desktop")
exec(mainMod .. " + R", "flatpak run org.gnome.World.PikaBackup")
exec(mainMod .. " + L", "~/.local/bin/lock-screen")
exec(mainMod .. " + space", "~/.local/bin/hypr-cheatsheet")
exec(mainMod .. " + V", 'cliphist list | rofi -dmenu -theme spotlight-dark -p "Clipboard" | cliphist decode | wl-copy')
exec(mainMod .. " + N", "swaync-client -t -sw")
exec(mainMod .. " + SHIFT + C", [[grim -g "$(slurp -p)" -t ppm - | convert - -format '%[hex:p{0,0}]' txt:- | tail -1 | cut -d' ' -f4 | wl-copy && notify-send "Color Copied" "$(wl-paste)"]])

hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + ESCAPE", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + grave", hl.dsp.workspace.toggle_special("scratchpad"))

-- Voice assistant. SUPER tapped alone toggles it, hence release.
-- Inert on a machine with no assistant installed.
exec("SUPER + SUPER_L", "kill -USR1 $(cat ~/.local/state/voice-assistant/voice-assistant.pid)", { release = true })
exec(mainMod .. " + SHIFT + V", "kill -USR2 $(cat ~/.local/state/voice-assistant/voice-assistant.pid)")
exec(mainMod .. " + M", "~/.local/bin/assistant --swap")

-- Volume / brightness / caps (SwayOSD)
exec("XF86AudioRaiseVolume", "swayosd-client --output-volume raise")
exec("XF86AudioLowerVolume", "swayosd-client --output-volume lower")
exec("XF86AudioMute",        "swayosd-client --output-volume mute-toggle")
exec("XF86AudioMicMute",     "swayosd-client --input-volume mute-toggle")
exec("Caps_Lock",            "swayosd-client --caps-lock", { locked = true })
exec("XF86MonBrightnessUp",   "swayosd-client --brightness raise")
exec("XF86MonBrightnessDown", "swayosd-client --brightness lower")
exec("XF86KbdBrightnessUp",   "brightnessctl -d spi::kbd_backlight set 10%+")
exec("XF86KbdBrightnessDown", "brightnessctl -d spi::kbd_backlight set 10%-")

-- Media keys
exec("XF86AudioPlay",  "playerctl play-pause")
exec("XF86AudioPause", "playerctl play-pause")
exec("XF86AudioNext",  "playerctl next")
exec("XF86AudioPrev",  "playerctl previous")
exec("XF86AudioStop",  "playerctl stop")

-- Screenshots
exec("Print", [[grim - | wl-copy && notify-send "Screen Captured" "Full screen -> Clipboard"]])
exec(mainMod .. " + F12", [[grim ~/Pictures/Screenshot-$(date +'%Y-%m-%d-%H-%M-%S').png && notify-send "Screen Captured" "Saved to ~/Pictures"]])
exec(mainMod .. " + SHIFT + S", [[grim -g "$(slurp -d)" - | wl-copy && notify-send "Region Captured" "Selection -> Clipboard"]])
exec(mainMod .. " + SHIFT + F12", [[grim -g "$(slurp -d)" ~/Pictures/Screenshot-$(date +'%Y-%m-%d-%H-%M-%S').png && notify-send "Region Captured" "Saved to ~/Pictures"]])
-- Annotate before saving — swappy opens the grab for arrows/text/blur, so
-- marking up a screenshot doesn't need a round trip through an image editor.
exec(mainMod .. " + SHIFT + A", [[grim -g "$(slurp -d)" - | swappy -f -]])

-- Screen recording
exec(mainMod .. " + SHIFT + R", [[pkill wf-recorder || wf-recorder -g "$(slurp)" -f ~/Videos/Recording-$(date +'%Y-%m-%d-%H-%M-%S').mp4 && notify-send "Recording Saved"]])
exec(mainMod .. " + ALT + R",   [[pkill wf-recorder || wf-recorder -f ~/Videos/Recording-$(date +'%Y-%m-%d-%H-%M-%S').mp4 && notify-send "Recording Saved"]])

-- Focus / move / resize
local dirs = { left = "left", right = "right", up = "up", down = "down" }
for key, dir in pairs(dirs) do
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ direction = dir }))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ direction = dir }))
end
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.window.resize({ x = -40, y = 0 }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 40,  y = 0 }))
hl.bind(mainMod .. " + CTRL + up",    hl.dsp.window.resize({ x = 0,   y = -40 }))
hl.bind(mainMod .. " + CTRL + down",  hl.dsp.window.resize({ x = 0,   y = 40 }))

-- Float / pin / center
hl.bind(mainMod .. " + SHIFT + F",     hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + P",     hl.dsp.window.pin())
hl.bind(mainMod .. " + SHIFT + space", hl.dsp.window.center())

-- Group (tabbed)
hl.bind(mainMod .. " + G",   hl.dsp.group.toggle())
hl.bind(mainMod .. " + TAB", hl.dsp.group.next())

-- Workspaces 1-10
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end
for i = 1, 5 do
    hl.bind(mainMod .. " + ALT + " .. i, hl.dsp.window.move({ workspace = i, silent = true }))
end

-- Mouse
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272",  hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273",  hl.dsp.window.resize(), { mouse = true })

------------------------------------------------------------------- DEVICES --
-- Prevent Razer keyboard from registering as a pointer (causes double cursor)
hl.device({ name = "razer-razer-blade-stealth-keyboard-1", enabled = false })

------------------------------------------------ MACHINE-LOCAL OVERRIDES ----
-- Last, so anything here wins over the settings above. setup.sh creates the
-- file empty and never overwrites it, which is the point: a config redeploy
-- must not undo a fix that is specific to one machine's hardware.
--
-- The case that earned this: a box driving a display off one of two GPUs needs
-- cursor.no_hardware_cursors = true. Redeploying the shared config set it back
-- to false and the compositor filled its log with "Backend requires blit, but
-- cursor blit failed" and froze the screen.
optional("local")
